SET AUTOCOMMIT = 0;
CREATE DATABASE ADE_KSR;
SET SQL_SAFE_UPDATES = 0;
USE ADE_KSR;
DROP TABLE CUST_INFO;
CREATE TABLE CUST_INFO(
CUST_NAME CHAR(20),
CUST_AGE INT,
CUST_LOC CHAR(20),
CUST_PHNO INT
);

INSERT INTO CUST_INFO VALUES("ARVIND",36,"GERMANY",1234567890);
SELECT * FROM CUST_INFO;



INSERT INTO CUST_INFO VALUES("SAMBHAVI",6,"BANGALORE",1234567890);
INSERT INTO CUST_INFO VALUES("HEMACHANDRA",9,"HYDERABAD",1324565780);
INSERT INTO CUST_INFO VALUES("NAKSHATRA",4,"ONGOLE",1324567890);
INSERT INTO CUST_INFO VALUES("LAXMAN",NULL,"GUNTUR",1567892340);
INSERT INTO CUST_INFO VALUES("NAGALAKSHMI",NULL,"BANGALORE",NULL);

UPDATE CUST_INFO SET CUST_LOC = "CANADA" WHERE CUST_NAME = "SAMBHAVI";
UPDATE CUST_INFO SET CUST_LOC = "HYDERABAD" WHERE CUST_NAME = "LAXMAN";
UPDATE CUST_INFO SET CUST_AGE = 35 WHERE CUST_NAME = "LAXMAN";
UPDATE CUST_INFO SET CUST_AGE = 29 WHERE CUST_NAME = "NAGALAKSHMI";

DELETE FROM CUST_INFO WHERE CUST_NAME = "NAGALAKSHMI";

--------------------------------------------

GRANT SELECT ON CUST_INFO TO SAMBHAVI;  # GRANTING ACCESS TO USER
GRANT SELECT(CUST_INFO,CUST_AGE,CUST_LOC) ON CUST_INFO TO SAMBHAVI;
GRANT INSERT ON CUST_INFO TO SAMBHAVI;

REVOKE SELECT ON CUST_INFO FROM SAMBHAVI; # REVOKE ACCESS FROM USER.

SELECT * FROM CUST_INFO;

ALTER TABLE CUST_INFO ADD COLUMN EMAIL CHAR(20);
UPDATE CUST_INFO SET EMAIL = "SAM@INFO.COM" WHERE CUST_NAME = "SAMBHAVI";
UPDATE CUST_INFO SET EMAIL = "HEMACHNADRA@INFO.COM" WHERE CUST_NAME = "HEMACHANDRA";
UPDATE CUST_INFO SET EMAIL = "NAKSHATRA@INFO.COM" WHERE CUST_NAME = "NAKSHATRA";
UPDATE CUST_INFO SET EMAIL = "LAXMAN@INFO.COM" WHERE CUST_NAME = "LAXMAN";
#-----------------------------------------------------------------------------------#
DROP TABLE CUST_TB;
CREATE TABLE CUST_TB(
CUST_NAME VARCHAR(20),
CUST_AGE INT,
CUST_LOC VARCHAR(20)
)
SELECT * FROM CUST_TB;

INSERT INTO CUST_TB VALUES ("SAM",22,"BANGALORE");
INSERT INTO CUST_TB VALUES ("HEM",25,"HYDERABAD");
INSERT INTO CUST_TB VALUES ("GOPI",29,"ONGOLE");
INSERT INTO CUST_TB VALUES ("SUMIT",34,"PATNA");
INSERT INTO CUST_TB VALUES ("SUBBU",38,"VIJAYAWADA");
START TRANSACTION ;
DELETE FROM CUST_TB WHERE CUST_NAME = "SAM";
SELECT * FROM CUST_TB;
ROLLBACK;
SELECT * FROM CUST_TB;

START TRANSACTION ;

UPDATE CUST_TB SET CUST_AGE = 99 WHERE CUST_NAME = "SUBBU";
UPDATE CUST_TB SET CUST_AGE = 88 WHERE CUST_NAME = "SUMIT";

SELECT * FROM CUST_TB;
ROLLBACK;
SELECT * FROM CUST_TB;

START TRANSACTION;
SAVEPOINT A; 
INSERT INTO CUST_TB VALUES ("RAJA",33,"CHENNAI");
SAVEPOINT B;
UPDATE CUST_TB SET CUST_AGE=99 WHERE CUST_NAME="GOPI";
SAVEPOINT C;
DELETE FROM CUST_TB;
SELECT * FROM CUST_TB;
ROLLBACK TO B;
SELECT * FROM CUST_TB;

SELECT * FROM CUST_TB;
START TRANSACTION;
SAVEPOINT M;
ALTER TABLE CUST_TB ADD COLUMN COMPANY VARCHAR(20);
SELECT * FROM CUST_TB;
SAVEPOINT N;
UPDATE CUST_TB SET COMPANY = "TCS";
SELECT * FROM CUST_TB;
ROLLBACK TO M;
SELECT * FROM CUST_TB;

#--------------------------------------------25th Sep - 2024 -----------------
DROP TABLE CUSTM_INFO;
CREATE TABLE CUSTM_INFO(
ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL,
AGE INT CHECK(AGE > 18),
ADDRESS VARCHAR(100) UNIQUE,
LOCATION VARCHAR(50) DEFAULT 'INDIA',
PHONE_NUMBER BIGINT CHECK(LENGTH(PHONE_NUMBER) = 10),
UNIQUE(PHONE_NUMBER),
CHECK(FIRST_NAME != LAST_NAME) 
);  

SELECT * FROM CUSTM_INFO;

INSERT INTO CUSTM_INFO VALUES (1,"MS","DHONI",39,"ALKAPURA,RANCHI","JHARKHAND",9365577777);
INSERT INTO CUSTM_INFO VALUES (2,"VIRAT","KOHLI",37,"RAJMARG,DELHI","NEWDELHI",9246751818);
INSERT INTO CUSTM_INFO VALUES (3,"CRISTIANO","RONALDO",45,"LAKESTREET,PRTCHUGAL","EUROPE",9277777777);
INSERT INTO CUSTM_INFO(ID,FIRST_NAME,LAST_NAME,AGE,ADDRESS,LOCATION,PHONE_NUMBER) 
VALUES (4,"RAKHI","BHAI",33,"GOLDSTREET,KOLAR","KARNATAKA",9879000012);
INSERT INTO CUSTM_INFO VALUES(5,"SUNIL","SHETTY",39,"CHURCHSTREET,SHORAPUR","KARNATAKA",9432112345);
INSERT INTO CUSTM_INFO VALUES(6,"JAYA","LALITHA",77,"POYASGARDEN,CHENNAI","TAMILNADU",9977654321);
INSERT INTO CUSTM_INFO (ID,FIRST_NAME,LAST_NAME,AGE,PHONE_NUMBER) 
VALUES(7,"NARENDRA","MODI",76,9999899997);

CREATE TABLE ORDER_INFO(
C_ID INT,
PRODUCT_NAME VARCHAR(20),
SALES INT,
FOREIGN KEY (C_ID) REFERENCES CUSTM_INFO(ID)
);
SELECT * FROM ORDER_INFO;
INSERT INTO ORDER_INFO VALUES(1,"PENDRIVE",299);
INSERT INTO ORDER_INFO VALUES(2,"GLUEGUN",499);
INSERT INTO ORDER_INFO VALUES(2,"LAPTOP",49999);
INSERT INTO ORDER_INFO VALUES(2,"MOBILE",9999);
INSERT INTO ORDER_INFO VALUES(8,"LAPTOP",49999);

#------------------------------------------------------------------------------

USE AMAZON_DB;
SELECT * FROM CAR_DATA;
SELECT * FROM CAR_DATA WHERE YEAR= 2014;
SELECT * FROM CAR_DATA WHERE YEAR = 2014 AND FUEL_TYPE = "PETROL" AND TRANSMISSION = "AUTOMATIC";
SELECT * FROM CAR_DATA WHERE YEAR IN(2014,2015);
SELECT * FROM CAR_DATA WHERE YEAR IN(2014,2015) AND FUEL_TYPE="PETROL" AND SELLER_TYPE = "DEALER";

SELECT CAR_NAME,SELLING_PRICE FROM CAR_DATA WHERE YEAR IN(2016,2017) AND FUEL_TYPE = "PETROL"
AND TRANSMISSION = "AUTOMATIC";

SELECT * FROM CAR_DATA WHERE YEAR IN (2014,2015) AND KMS_DRIVEN > 10000;

SELECT * FROM CAR_DATA WHERE YEAR IN(2015,2014) AND KMS_DRIVEN > 50000 ORDER BY KMS_DRIVEN DESC;

SELECT DISTINCT CAR_NAME FROM CAR_DATA;
SELECT * FROM CAR_DATA;
SELECT DISTINCT TRANSMISSION FROM CAR_DATA;

SELECT DISTINCT FUEL_TYPE FROM CAR_DATA;

#------------------------------------------------------------------------------

SELECT * FROM CAR_DATA;
SELECT COUNT(*) FROM CAR_DATA;
SELECT COUNT(*) FROM CAR_DATA WHERE FUEL_TYPE = "PETROL"; #239
SELECT COUNT(*) FROM CAR_DATA WHERE FUEL_TYPE = "DIESEL"; #60
SELECT COUNT(*) FROM CAR_DATA WHERE FUEL_TYPE = "CNG"; #2
SELECT COUNT(*) FROM CAR_DATA WHERE TRANSMISSION = "MANUAL"; #261
SELECT COUNT(*) FROM CAR_DATA WHERE TRANSMISSION = "AUTOMATIC"; #40

SELECT COUNT(*) FROM CAR_DATA WHERE YEAR IN ("2014","2015");
SELECT COUNT(*) FROM CAR_DATA WHERE YEAR NOT IN ("2014","2015");
SELECT COUNT(CAR_NAME) FROM CAR_DATA;
SELECT COUNT(DISTINCT CAR_NAME) FROM CAR_DATA;
SELECT COUNT(DISTINCT FUEL_TYPE) FROM CAR_DATA;
SELECT DISTINCT FUEL_TYPE FROM CAR_DATA;
SELECT DISTINCT YEAR FROM CAR_DATA ORDER BY YEAR ASC;
SELECT MIN(YEAR) FROM CAR_DATA;
SELECT MAX(YEAR) FROM CAR_DATA;

SELECT COUNT(TRANSMISSION) FROM CAR_DATA WHERE TRANSMISSION = "AUTOMATIC";
SELECT COUNT(TRANSMISSION) FROM CAR_DATA WHERE TRANSMISSION = "MANUAL";

SELECT MIN(KMS_DRIVEN) FROM CAR_DATA;
SELECT MAX(KMS_DRIVEN) FROM CAR_DATA;
SELECT MIN(KMS_DRIVEN),MAX(KMS_DRIVEN) FROM CAR_DATA;

SELECT MIN(SELLING_PRICE),MAX(SELLING_PRICE) FROM CAR_DATA;
SELECT DISTINCT CAR_NAME FROM CAR_DATA WHERE YEAR BETWEEN 2014 AND 2017;

SELECT COUNT(CAR_NAME) FROM CAR_DATA WHERE KMS_DRIVEN >100000;
SELECT COUNT(CAR_NAME) FROM CAR_DATA WHERE KMS_DRIVEN BETWEEN 10000 AND 400000;
SELECT * FROM CAR_DATA WHERE KMS_DRIVEN BETWEEN 100000 AND 400000 ORDER BY KMS_DRIVEN DESC;

SELECT * FROM CAR_DATA WHERE SELLING_PRICE BETWEEN 5.0 AND 15.0;

SELECT YEAR,COUNT(CAR_NAME) FROM CAR_DATA GROUP BY YEAR ORDER BY COUNT(CAR_NAME);
SELECT CAR_NAME,COUNT(CAR_NAME) FROM CAR_DATA GROUP BY CAR_NAME ORDER BY COUNT(CAR_NAME);
SELECT * FROM CAR_DATA;
SELECT FUEL_TYPE,COUNT(CAR_NAME) FROM CAR_DATA GROUP BY FUEL_TYPE;
SELECT TRANSMISSION,COUNT(CAR_NAME) FROM CAR_DATA GROUP BY TRANSMISSION;

SELECT FUEL_TYPE,TRANSMISSION,COUNT(CAR_NAME) FROM CAR_DATA GROUP BY FUEL_TYPE,TRANSMISSION;

#----------------------------Assignment1----------------------------------------------#
USE AMAZON_DB;
SELECT * FROM ELE_STORE;

#1) How many total number of orders placed?
SELECT COUNT(ORDERID) AS TOTAL_ORDERS FROM ELE_STORE;  #15000

#2) What are the unique channels present and how many are there?
SELECT DISTINCT CHANNEL FROM ELE_STORE; #STORE, ONLINE, RESELLER, CATALOG
SELECT COUNT(DISTINCT CHANNEL) TOTAL_CHANNELS FROM ELE_STORE; #4

#3) How many cities are there?
SELECT COUNT(DISTINCT CITY) FROM ELE_STORE; #263

#4) Query the total cities count by Country
SELECT COUNTRY,COUNT(CITY) TOTAL_CITY FROM ELE_STORE GROUP BY COUNTRY;

#5) How many products are there?
SELECT COUNT(DISTINCT PRODUCTNAME) TOTAL_PRODUCTS FROM ELE_STORE; #1638

#6) Query the total sales and total profit?
SELECT SUM(SALES),SUM(PROFIT) FROM ELE_STORE; #SALES = '55391759.78809967', #PROFIT '31587437.287211794'

#7) Query the total sales by region and country?
SELECT REGION,COUNTRY,SUM(SALES) FROM ELE_STORE GROUP BY REGION,COUNTRY ;

#8) Query the total order qty by promotion name?
SELECT PROMOTIONNAME,SUM(ORDERQTY) FROM ELE_STORE GROUP BY PROMOTIONNAME;

#9) How much the total sales happened in Asia region?
SELECT SUM(SALES) FROM ELE_STORE WHERE REGION = 'ASIA'; #'12412345.056500021'

#10) How much profit got in Asia region and India?
SELECT SUM(PROFIT) FROM ELE_STORE WHERE REGION = 'ASIA' ; #'7144693.834823994'
SELECT SUM(PROFIT) FROM ELE_STORE WHERE COUNTRY = 'INDIA'; #'357657.327792167'

#11) Query the total order qty by Manufacturer and Product Name?
SELECT MANUFACTURER,PRODUCTNAME,SUM(ORDERQTY) FROM ELE_STORE GROUP BY MANUFACTURER,PRODUCTNAME;
USE ADE_KSR;
#12) Query the total order quantity greater than 27 by city?
SELECT CITY FROM ELE_STORE WHERE ORDERQTY > 27 GROUP BY CITY;

#13) How much total sales happened in China and Beijing?
SELECT SUM(SALES) FROM ELE_STORE WHERE COUNTRY = 'CHINA' AND CITY = 'BEIJING'; #'6596953.095500005'

#14) How much total sales happened in Asian Holiday Promotion?
SELECT SUM(SALES) FROM ELE_STORE WHERE  PROMOTIONNAME = 'ASIAN HOLIDAY PROMOTION'; #'3615193.9904999994'

#15) How much total profit value by Contoso, Ltd Manufacturer?
SELECT SUM(PROFIT) FROM ELE_STORE WHERE MANUFACTURER = "CONTOS LTD";

#16) Query the total sales and total order qty by productcategory?
SELECT PRODUCTCATEGORY,SUM(SALES) AS TOTAL_SALES,SUM(ORDERQTY) TOTAL_ORDERQTY FROM ELE_STORE GROUP BY PRODUCTCATEGORY;

#17) Query the total sales value in between 1057 and 26700 by Region?
SELECT REGION, SALES FROM ELE_STORE  WHERE SALES BETWEEN 1057 AND 26700 ;

#18) How many orders placed in Pittsfield city?
SELECT COUNT(ORDERID) AS TOTAL_ORDERQTY FROM ELE_STORE WHERE CITY = 'PITTSFIELD'; #31

#19) Query the total sales and total profit by region, country and city?
SELECT REGION,COUNTRY,CITY,SUM(SALES),SUM(PROFIT) FROM ELE_STORE GROUP BY REGION,COUNTRY,CITY ORDER BY REGION;

#20) Query the total unit cost and total price by productcategory, productsubcategory and Manufacturer?
SELECT PRODUCTCATEGORY,PRODUCTSUBCATEGORY,MANUFACTURER ,SUM(UNITCOST),SUM(PRICE) FROM ELE_STORE
GROUP BY PRODUCTCATEGORY,PRODUCTSUBCATEGORY,MANUFACTURER;


#---------------------------3rd Oct 2024------------------------------------
USE AMAZON_DB;
SELECT * FROM AMAZON_DB.CUSTUMER_TB;
SELECT CUSTUMER_TB.NAME,CUSTUMER_TB.ADDRESS FROM AMAZON_DB.CUSTUMER_TB;
SELECT A.NAME,A.ADDRESS FROM AMAZON_DB.CUSTUMER_TB A;
SELECT * FROM AMAZON_DB.ORDER_TB;
SELECT B.DATE,B.AMOUNT FROM AMAZON_DB.ORDER_TB B;

SELECT A.NAME, A.ADDRESS, B.OID, B.DATE FROM CUSTUMER_TB A
INNER JOIN ORDER_TB B  ON A.ID = B.C_ID;  #INNERJOIN

SELECT A.NAME,A.ADDRESS, B.OID,B.DATE FROM CUSTUMER_TB A LEFT JOIN
ORDER_TB B ON A.ID = B.C_ID;

SELECT A.NAME,A.ADDRESS,B.OID,B.DATE FROM CUSTUMER_TB A RIGHT JOIN
ORDER_TB B ON A.ID = B.C_ID;

SELECT A.NAME,A.ADDRESS,B.OID,B.DATE FROM CUSTUMER_TB A FULL JOIN
ORDER_TB B ON A.ID = B.C_ID;

SELECT * FROM CUST_INFO;
SELECT * FROM KSR_DB.NCC_JHANSI_STAFFINFO;
SELECT * FROM KSR_DB.STAFF_SALARY_DETAILS;

SELECT * FROM KSR_DB.NCC_JHANSI_STAFFINFO A INNER JOIN KSR_DB.STAFF_SALARY_DETAILS B 
ON A.EMP_ID = B.EMP_ID;

#---------------------------4th Oct 2024--------------------------

USE ADE_KSR;

SELECT * FROM CUST_INFO;
SELECT * FROM CUST_TB;

CREATE TABLE TEST_DB1(
ID INT,
PHONE_NUMBER BIGINT,
NAME VARCHAR(50));

INSERT INTO TEST_DB1 VALUES(1,9878901234,"RAMESH");
INSERT INTO TEST_DB1 VALUES(2,8907345612,"SRINU");
INSERT INTO TEST_DB1 VALUES(3,9000878345,"ALBERT");

SELECT * FROM TEST_DB1;

CREATE TABLE TEST_DB2(
ID INT,
NAME VARCHAR(50),
PHONE_NUMBER BIGINT
);

INSERT INTO TEST_DB2 VALUES(4,"KASIM",9823567788);
INSERT INTO TEST_DB2 VALUES(5,"VINAYAK",7684092400);
INSERT INTO TEST_DB2 VALUES(6,"PRASHANT",7854201999);
INSERT INTO TEST_DB2 VALUES(3,"ALBERT",9000878345);

SELECT * FROM TEST_DB2;  


SELECT ID, NAME, PHONE_NUMBER FROM TEST_DB1
UNION
SELECT ID, NAME, PHONE_NUMBER FROM TEST_DB2; #DUPLICATED RECORD EXCLUDED

SELECT ID, NAME, PHONE_NUMBER FROM TEST_DB1
UNION ALL
SELECT ID, NAME, PHONE_NUMBER FROM TEST_DB2; # DUPLICATE RECORD INCLUDED 


SELECT * FROM AMAZON_DB.CUSTUMER_TB; #ID,NAME, ADDRESS
SELECT * FROM AMAZON_DB.ORDER_TB; #OID,DATE

SELECT A.ID,A.NAME,A.ADDRESS,B.OID,B.DATE FROM AMAZON_DB.CUSTUMER_TB A LEFT JOIN 
AMAZON_DB.ORDER_TB B ON A.ID = B.C_ID
UNION 
SELECT A.ID,A.NAME,A.ADDRESS,B.OID,B.DATE FROM AMAZON_DB.CUSTUMER_TB A RIGHT JOIN
AMAZON_DB.ORDER_TB B ON A.ID = B.C_ID; 

SELECT COUNT(DISTINCT A.NAME) FROM AMAZON_DB.CUSTUMER_TB A INNER JOIN 
AMAZON_DB.ORDER_TB B ON A.ID = B.C_ID;

#TOTAL CUSTMERS 
SELECT COUNT(DISTINCT A.NAME) FROM AMAZON_DB.CUSTUMER_TB A LEFT JOIN
AMAZON_DB.ORDER_TB B ON A.ID = B.C_ID;

#TOTAL CUSTOMER WHO DIDN'T PURCHASE
SELECT COUNT( DISTINCT A.NAME) FROM AMAZON_DB.CUSTUMER_TB A LEFT JOIN
AMAZON_DB.ORDER_TB B ON A.ID = B.C_ID
WHERE OID IS NULL;

#GUEST ORDERS
SELECT COUNT(B.OID) FROM AMAZON_DB.CUSTUMER_TB A RIGHT JOIN 
AMAZON_DB.ORDER_TB B ON A.ID = B.C_ID
WHERE A.ID IS NULL;

#--------------------------------7th Oct ---------------------------------------

USE POWER_APPS;

SELECT * FROM BIKE_DATA;

SELECT * FROM BIKE_DATA LIMIT 100;  

SELECT SUM(SALES) AS TOTALSALES FROM BIKE_DATA;

SELECT COUNTRY,SUM(SALES) AS TOTALSALES FROM BIKE_DATA GROUP BY COUNTRY;

SELECT COUNTRY, SUM(SALES) AS TOTALSALES FROM BIKE_DATA 
GROUP BY COUNTRY HAVING TOTALSALES > 2500000 ORDER BY TOTALSALES DESC;

SELECT * FROM (SELECT COUNTRY, SUM(SALES) AS TOTALSALES FROM BIKE_DATA GROUP BY COUNTRY) 
A WHERE TOTALSALES > 2500000 ORDER BY TOTALSALES DESC; 

SELECT * FROM BIKE_DATA;

SELECT  * FROM 
(SELECT REGION, COUNTRY, CATEGORY,SUM(SALES) AS TOTALSALES, SUM(PROFIT) AS TOTALPROFIT 
FROM BIKE_DATA GROUP BY REGION, COUNTRY, CATEGORY)  A WHERE TOTALPROFIT  > 1000000;	

SELECT * FROM STUDENT_TB;

USE AMAZON_DB;

SELECT * FROM STUDENT_MARKS_TB; 
SELECT NAME FROM STUDENT_MARKS_TB ORDER BY MARKS DESC LIMIT 1; 

SELECT * FROM TCL_TB;

USE GDB023;

SELECT * FROM DIM_CUSTOMER;
SELECT * FROM DIM_PRODUCT;
SELECT * FROM FACT_MANUFACTURING_COST;

SELECT * FROM DIM_PRODUCT A LEFT JOIN FACT_MANUFACTURING_COST B ON A.PRODUCT_CODE = B.PRODUCT_CODE; 

SELECT * FROM (SELECT A.PRODUCT_CODE,A.DIVISION,A.CATEGORY,B.COST_YEAR,B.MANUFACTURING_COST FROM DIM_PRODUCT A INNER JOIN 
FACT_MANUFACTURING_COST B ON A.PRODUCT_CODE = B.PRODUCT_CODE) C
WHERE MANUFACTURING_COST > 230 ORDER BY MANUFACTURING_COST DESC;

USE ADE_KSR;

CREATE TABLE department(
	id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE company(
	id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    revenue INT
);

CREATE TABLE Employee(
	id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    city VARCHAR(150) NOT NULL,
    department_id INT NOT NULL,
    salary INT NOT NULL,
    FOREIGN KEY (department_id) REFERENCES department(id)
);

INSERT INTO department(name)
VALUES
('IT'),
('Management'),
('IT'),
('Support');

INSERT INTO company(name,revenue)
VALUES
('IBM', 2000000),
('GOOGLE', 9000000),
('Apple', 10000000);

INSERT INTO employee (name,city,department_id,salary)
VALUES
('David', 'London', 3, 80000),
('Emily', 'London', 3, 70000),
('Peter', 'Paris', 3, 60000),
('Ava', 'Paris', 3, 50000),
('Penny', 'London', 2, 110000),
('Jim', 'London', 2, 90000),
('Amy', 'Rome', 4, 30000),
('Cloe', 'London', 3, 110000);

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT * FROM COMPANY;

#--------------------------8th Oct 2024--------------------------------------

USE AMAZON_DB;

SELECT * FROM STUDENT_MARKS_TB;

SELECT *, RANK() OVER(ORDER BY MARKS DESC) AS RNK FROM STUDENT_MARKS_TB;
SELECT NAME FROM (
SELECT *, RANK() OVER(ORDER BY MARKS DESC) AS RNK FROM STUDENT_MARKS_TB) A
WHERE RNK = 4;


SELECT * FROM(
SELECT *, DENSE_RANK() OVER(ORDER BY MARKS DESC) AS RNK FROM STUDENT_MARKS_TB) A 
WHERE RNK = 6;

SELECT * FROM(
SELECT NAME,MARKS, ROW_NUMBER() OVER(ORDER BY MARKS DESC) AS RNK FROM STUDENT_MARKS_TB) A 
WHERE RNK = 6;

SELECT * FROM STUDENT_MARKS_TB_1;

SELECT * FROM(
SELECT NAME, MEDIUM, DENSE_RANK() OVER(PARTITION BY MEDIUM ORDER BY MARKS DESC) AS RNK 
FROM STUDENT_MARKS_TB_1) A WHERE RNK = 2 AND MEDIUM = "ENGLISH"; 

SELECT * FROM  ELE_STORE;

SELECT * FROM (
SELECT REGION,COUNTRY, DENSE_RANK() OVER(PARTITION BY REGION ORDER BY SUM(ORDERQTY) DESC) AS RNK 
FROM ELE_STORE GROUP BY REGION,COUNTRY ) A WHERE RNK = 2;

SELECT * FROM ORDER_TB;

USE KSR_DB;

SELECT * FROM NCC_JHANSI_STAFFINFO;
SELECT * FROM STAFF_SALARY_DETAILS;

SELECT * FROM(
SELECT *,RANK() OVER(ORDER BY TOTAL_PAY DESC) AS RNK FROM(
SELECT A.EMP_NAME,A.EMP_PHNO,A.EMP_LOC, B.NET_PAY, B.TOTAL_PAY FROM NCC_JHANSI_STAFFINFO A INNER JOIN
STAFF_SALARY_DETAILS B ON A.EMP_ID = B.EMP_ID) A ) B WHERE RNK =7 ;



#------------------------------9th Oct 2024-----------------------------

USE ADE_KSR;

CREATE TABLE WINDOWS_FUNS(
S_YEAR INT,
T_SALES INT
);
INSERT INTO WINDOWS_FUNS(S_YEAR,T_SALES) VALUES
(2020,15000),(2021,18000),(2022,14500),(2023,16000),(2024,17500);

SELECT * FROM WINDOWS_FUNS;

SELECT S_YEAR,T_SALES, ((T_SALES - P_SALES)/P_SALES)*100 AS YoY FROM(
SELECT S_YEAR,T_SALES,LAG(T_SALES) OVER(ORDER BY S_YEAR) AS P_SALES FROM WINDOWS_FUNS) A;

SELECT S_YEAR,T_SALES,LEAD(T_SALES) OVER(ORDER BY S_YEAR) AS P_SALES FROM WINDOWS_FUNS;
#LAG/LEAD IS PARAMETER LEAD(T_SALES,1) IT WILL GO 1 STEP BELOW

CREATE TABLE WINDOWS_FUNS_1(
S_YEAR INT,
S_PRODUCT VARCHAR(20),
T_SALES INT
);

INSERT INTO WINDOWS_FUNS_1(S_YEAR,S_PRODUCT,T_SALES) VALUES
(2015,'IPHONE',23000),(2016,'IPHONE',25000),(2017,'IPHONE',34000),(2018,'IPHONE',32000),(2019,'IPHONE',45000),
(2015,'SAMSUNG',21000),(2016,'SAMSUNG',20000),(2017,'SAMSUNG',31500),(2018,'SAMSUNG',29700),(2019,'SAMSUNG',34500);

SELECT * FROM WINDOWS_FUNS_1;

SELECT S_YEAR,S_PRODUCT,((T_SALES - P_SALES)/P_SALES) * 100  YoY FROM(
SELECT S_YEAR,S_PRODUCT,T_SALES,LAG(T_SALES) OVER(PARTITION BY S_PRODUCT  ORDER BY S_YEAR) AS P_SALES 
FROM WINDOWS_FUNS_1) T;

CREATE TABLE STUDENT_MARKSTB(
S_NAME VARCHAR(20),
S_SUBJECT VARCHAR(20),
MARKES INT
);

INSERT INTO STUDENT_MARKSTB (S_NAME, S_SUBJECT, MARKES) VALUES 
('SANTOSH','MATHS',99),('SANTOSH','SCEINCE',85),('SANTOSH','COMPUTERS',94),
('RAHUL','MATHS',98),('RAHUL','SCEINCE',84),('RAHUL','COMPUTERS',89),
('SATHISH','MATHS',98),('SATHISH','SCEINCE',98),('SATHISH','COMPUTERS',98),
('DIVI','MATHS',96),('DIVI','SCEINCE',92),('DIVI','COMPUTERS',91);

SELECT * FROM STUDENT_MARKSTB;

SELECT * FROM (
SELECT S_NAME, TTLMRKS, RANK() OVER(ORDER BY TTLMRKS DESC) AS RNK FROM(
SELECT S_NAME, SUM(MARKES) AS TTLMRKS FROM STUDENT_MARKSTB GROUP BY S_NAME) A)
B WHERE RNK = 2 ;

WITH CTE AS (
(SELECT S_NAME, SUM(MARKES) AS TTLMARKS FROM STUDENT_MARKSTB GROUP BY S_NAME)),
CTE1 AS (
SELECT *, RANK() OVER(ORDER BY TTLMARKS DESC) AS RNK  FROM CTE)
SELECT * FROM CTE1 WHERE RNK = 2 ;

#--------------------------------------------10th Oct 2024----------------------
USE AMAZON_DB;

SELECT * FROM ELE_STORE;

SELECT COUNTRY, SUM(SALES), AVG(PROFIT) FROM ELE_STORE GROUP BY COUNTRY; #AGGRGATE FUNCTIONS

SELECT REGION , COUNTRY, UPPER(COUNTRY), LENGTH(COUNTRY) FROM ELE_STORE; #SCALER FUNCTIONS

SELECT REGION, COUNTRY, AVG(SALES), SUM(PROFIT) FROM ELE_STORE GROUP BY REGION, COUNTRY;
SELECT REGION, COUNTRY, ROUND(AVG(SALES),2), ROUND(SUM(PROFIT),2) FROM ELE_STORE GROUP BY REGION, COUNTRY;

SELECT * FROM ELE_STORE;

SELECT REGION,COUNTRY,CITY, SUM(SALES), AVG(PROFIT) FROM ELE_STORE 
GROUP BY REGION, COUNTRY, CITY
ORDER BY SUM(SALES),AVG(PROFIT);

SELECT REGION,COUNTRY,CITY, SUM(SALES), AVG(PROFIT) FROM ELE_STORE
GROUP BY 1,2,3 ORDER BY 4,5;
 
 SELECT MIN(ORDERDATE) FROM ELE_STORE;

SELECT YEAR(ORDERDATE), SUM(SALES), SUM(PROFIT) FROM ELE_STORE
GROUP BY 1
ORDER BY 1;


SELECT YR, T_SALES, P_SALES, ((T_SALES - P_SALES)/P_SALES) * 100 AS YoY FROM
(SELECT YR , T_SALES, LAG(T_SALES) OVER(ORDER BY YR) AS P_SALES FROM 
(SELECT YEAR(ORDERDATE)YR , SUM(SALES) T_SALES FROM ELE_STORE
GROUP BY YR) A) B;


WITH CTE1 AS (
SELECT YEAR(ORDERDATE) YR, SUM(SALES) T_SALES FROM ELE_STORE GROUP BY 1 ORDER BY 1),
CTE2 AS (SELECT YR, T_SALES, LAG(T_SALES) OVER(ORDER BY YR) P_SALES FROM CTE1 ),
CTE3 AS (SELECT YR, T_SALES, P_SALES, ((T_SALES - P_SALES)/P_SALES) * 100 AS YoY FROM CTE2)
SELECT * FROM CTE3;

#----------------------------------------14th Oct 24 -----------------------------------------

USE ADE_KSR;

SELECT TRANSMISSION, COUNT(CAR_NAME) AS TOTAL_CARS FROM CAR_DATA
WHERE YEAR = 2014
GROUP BY TRANSMISSION
ORDER BY TRANSMISSION;

SELECT TRANSMISSION, COUNT(CAR_NAME) AS TOTAL_CARS FROM CAR_DATA
WHERE YEAR = 2015
GROUP BY TRANSMISSION
ORDER BY TRANSMISSION;

DELIMITER &&
CREATE PROCEDURE GETTRANSMISSIONCARS(
IN YR INT
)
BEGIN
SELECT TRANSMISSION,COUNT(CAR_NAME) AS TOTAL_CARS FROM CAR_DATA
WHERE YEAR = YR
GROUP BY TRANSMISSION
ORDER BY TRANSMISSION;
END
&&

CALL GETTRANSMISSIONCARS(2016);

DELIMITER &&
CREATE PROCEDURE GETFUETYPESELPRICE(
IN FULTYPE VARCHAR(20)
)
BEGIN
SELECT SUM(SELLING_PRICE) AS SELL_PRICE FROM CAR_DATA
WHERE FUEL_TYPE = FULTYPE;
END
&&
CALL GETFUETYPESELPRICE("PETROL");
CALL GETFUETYPESELPRICE("DIESEL");

SELECT * FROM CAR_DATA;

DROP PROCEDURE GETCARDATA;

DELIMITER &&
CREATE PROCEDURE GETCARDATA(
IN YR INT,
IN FUL_TYPE VARCHAR(20)
)
BEGIN
SELECT YEAR,COUNT(CAR_NAME) AS TOTALCAR_COUNT, SUM(SELLING_PRICE) AS SELPRICE, SUM(PRESENT_PRICE) AS PRSNTPRICE
FROM CAR_DATA WHERE YEAR = YR AND FUEL_TYPE = FUL_TYPE
GROUP BY YEAR
ORDER BY TOTALCAR_COUNT DESC;
END
&&

CALL GETCARDATA(2014,"PETROL");

USE ADE_KSR;

SELECT * FROM TATA_TB1;
SELECT * FROM TATA_TB2;

SELECT * FROM TATA_TB1 A INNER JOIN TATA_TB2 B ON A.ORDERID = B.ORDERID;

SELECT REGION, SUM(SALES) AS TOTAL_SALES FROM(
SELECT A.REGION,A.COUNTRY,A.CITY,B.SALES,PROFIT 
FROM TATA_TB1 A INNER JOIN TATA_TB2 B 
ON A.ORDERID = B.ORDERID) A
GROUP BY REGION;

DROP PROCEDURE GETREGIONSALES;
DELIMITER &&
CREATE PROCEDURE GETREGIONSALES(
IN RGION VARCHAR(20) 
)
BEGIN
SELECT * FROM (
SELECT REGION, SUM(SALES) AS TOTAL_SALES FROM(
SELECT A.REGION,A.COUNTRY,B.SALES,B.PROFIT
FROM TATA_TB1 A INNER JOIN TATA_TB2 B 
ON A.ORDERID = B.ORDERID) A GROUP BY REGION) B
WHERE REGION = RGION;
END
&& ##----------WITH IN PARAMETER

CALL GETREGIONSALES("SOUTH");


#----------------------15th Oct 2024------------------------------------------------
USE ADE_KSR;
SELECT * FROM SUPER_STORE_TB;
DELIMITER &&
CREATE PROCEDURE CUSTOMER_SALES_STATUS(
IN R_ID INT,
OUT R_STATUS VARCHAR(30)
)
BEGIN
DECLARE TOTALSALES INT DEFAULT 0;
SELECT SUM(SALES) INTO TOTALSALES FROM SUPER_STORE_TB
WHERE ROWID = R_ID;
IF TOTALSALES > 15000 THEN
		SET R_STATUS = 'PLATINUMCUSTOMER';
ELSEIF TOTALSALES <= 5000 THEN
		SET R_STATUS = 'SILVERCUSTOMER';
ELSE        
		SET R_STATUS = 'GOLDCUSTOMER';
END IF;        
END;
&&

CALL CUSTOMER_SALES_STATUS(4099,@R_STATUS);
SELECT @R_STATUS;

SELECT ROWID,SUM(SALES) AS TOTAL_SALES FROM SUPER_STORE_TB
GROUP BY ROWID ORDER BY TOTAL_SALES DESC;

SELECT SALES FROM SUPER_STORE_TB WHERE ROWID = 4099;
SELECT * FROM SUPER_STORE_TB;

CREATE TABLE SALESTB(
USER_ID INT,
SALES INT,
DATE CHAR(20)
)
SELECT USER_ID,SUM(SALES) FROM SALESTB GROUP BY USER_ID;
INSERT INTO SALESTB VALUES(1,2000,"2019-10-12")
INSERT INTO SALESTB (USER_ID,SALES,DATE) VALUES(1,4000,"2018-10-11"),(1,2500,"2019-08-08"),
(2,2200,"2019-07-18"),(2,4000,"2019-12-18"),(2,4000,"2018-01-11"),
(3,2500,"2019-10-22"),(3,1500,"2018-02-12"),(3,3000,"2019-05-10"),
(4,1500,"2019-07-14"),(4,2600,"2018-06-18"),(4,5000,"2019-07-22");

DROP PROCEDURE CUSTOMER_STATUS;
DELIMITER &&
CREATE PROCEDURE CUSTOMER_STATUS(
IN V_ID INT,
OUT V_STATUS VARCHAR(30)
)
BEGIN
DECLARE PURCHASE INT DEFAULT 0;
SELECT SUM(SALES) INTO PURCHASE FROM SALESTB
WHERE USER_ID = V_ID;
IF PURCHASE > 9000 THEN
       SET V_STATUS = "PLATINUM_CUSTOMER";
ELSEIF PURCHASE <=8000 THEN
       SET V_STATUS = "SILVER_CUSTOMER";
ELSE
       SET V_STATUS = "GOLD_CUSTOMER";       
END IF;
END;
&& ###----------WITH IN & OUT PARAMETER

CALL CUSTOMER_STATUS(2,@V_STATUS);
SELECT @V_STATUS;


#car_data
#TOP5 YEARS WITH HIGHEST CAR_COUNT

DELIMITER &&
CREATE PROCEDURE TOP5YEARCARCOUNT()
BEGIN
WITH CTE1 AS (
SELECT YEAR,COUNT(CAR_NAME) AS TOTAL_CARS FROM CAR_DATA
GROUP BY YEAR),
CTE2 AS (
SELECT *, RANK() OVER(ORDER BY TOTAL_CARS DESC)RNK FROM CTE1)
SELECT * FROM CTE2 WHERE RNK <=5;
END;
&& ###----------WITH OUT IN & OUT PARAMETER

CALL TOP5YEARCARCOUNT();

#------------FUNCTIONS--------------------------
DELIMITER &&
CREATE FUNCTION SALESCALCULATION
(
LISTPRICE INT, 
ORDERQTY INT
)
RETURNS INT
DETERMINISTIC
BEGIN
DECLARE SALES INT; 
SET SALES = LISTPRICE * ORDERQTY;
RETURN SALES;
END
&&

SELECT SALESCALCULATION(2400,7) AS SALES;


#-----------------------FUNCTION 2ND EXAMPLE-------------------------------------
DELIMITER &&
CREATE FUNCTION F_CUST_AGE_GROUP(
AGE INT)
RETURNS VARCHAR(20)
DETERMINISTIC
BEGIN
DECLARE CUST_AGE_GROUP VARCHAR(20);
IF AGE <= 18 THEN
       SET CUST_AGE_GROUP = 'TEEN';
ELSEIF (AGE <=45 AND AGE >= 19) THEN
       SET CUST_AGE_GROUP = 'ADULT';
ELSEIF AGE > 45  THEN
       SET CUST_AGE_GROUP = 'SENIOR CITIZEN';
END IF;
RETURN  (CUST_AGE_GROUP) ; 
END
&&

SELECT F_CUST_AGE_GROUP(52) AS AGE;

SELECT *,F_CUST_AGE_GROUP(CUST_AGE) AS AGEGRP FROM CUST_TB; # WE ARE APPLYING FUNCTION TO EXISTING TABLE.VIFE

#----------------------------------------------------oooooooooooooo-------------

DELIMITER &&
CREATE PROCEDURE CUSTSTATUS(
IN I_ID INT,
OUT I_STATUS VARCHAR(30)
)
BEGIN
DECLARE TOTALSALES INT DEFAULT 0 ;
SELECT SUM(SALES) INTO TOTALSALES FROM SUPER_STORE_TB
WHERE ROWID = I_ID;
IF TOTALSALES > 15000 THEN
		SET I_STATUS = "PLATINUM";
ELSEIF TOTALSALES <= 6000 THEN
	    SET I_STATUS = "SILVER";
ELSE 
        SET I_STATUS = "GOLD";        
END IF;
END
&&
CALL CUSTSTATUS(2624,@I_STATUS);
SELECT @I_STATUS;

SELECT * FROM SUPER_STORE_TB;
# TOP5 CITIES WITH HIGHEST SALES

DELIMITER &&
CREATE PROCEDURE TOP5CITIES()
BEGIN
WITH CTE1 AS (
SELECT CITY,ROUND(SUM(SALES),2) AS TOTALSALES FROM SUPER_STORE_TB GROUP BY CITY),
CTE2 AS(SELECT *, RANK() OVER(ORDER BY TOTALSALES DESC) AS RNK FROM CTE1)
SELECT * FROM CTE2 WHERE RNK <=5;
END;
&&
CALL TOP5CITIES();

#---------------------FUNCTIONS---------------------
DROP FUNCTION COSTCALCU;
DELIMITER &&
CREATE FUNCTION COSTCALCU(
UNITPRICE INT,
ORDERQTY INT)
RETURNS INT 
DETERMINISTIC 
BEGIN
DECLARE COST INT;
SET COST = UNITPRICE * ORDERQTY;
RETURN COST;
END;
&&

SELECT COSTCALCU (1570,7) AS COST;
SELECT COSTCALCU (1280,11) AS COST;

DELIMITER &&
CREATE FUNCTION F_CUST_AGE_GRP(
AGE INT)
RETURNS VARCHAR(20)
DETERMINISTIC
BEGIN
DECLARE CUST_AGE_GROUP VARCHAR(20);
IF AGE <=18 THEN
	SET CUST_AGE_GROUP = 'TEEN';
ELSEIF (AGE <= 45 AND AGE > 18) THEN
	SET CUST_AGE_GROUP = 'ADULT';
ELSEIF AGE > 45 THEN
	SET CUST_AGE_GROUP = 'SENIOR CITIZEN';
END IF;    
RETURN (CUST_AGE_GROUP)   ;     
END;
&&

SELECT F_CUST_AGE_GRP(37) AS AGEGROUP;
SELECT *, F_CUST_AGE_GRP(CUST_AGE) AS AGEGROUP FROM CUST_TB;

#---------------------------16th Oct 2024-------------------------------------------------
SELECT * FROM CUSTM_INFO; #-------TRIGGERS.....
DROP TABLE CUSTM_LOG;
CREATE TABLE CUSTM_LOG(
ID INT AUTO_INCREMENT PRIMARY KEY,
ID1 INT,
ACTION VARCHAR(20),
FIELD VARCHAR(20),
OLD_VALUE VARCHAR(20),
NEW_VALUE VARCHAR(20),
UPDATEUSER VARCHAR(20),
UPDATETIMESTAMP TIMESTAMP);
UPDATE CUSTM_INFO SET LOCATION = "DELHI" WHERE ID = 3;
SELECT * FROM CUSTM_LOG;

DROP TRIGGER CUSTM_TRIGGER;
DELIMITER &&
CREATE TRIGGER CUSTM_TRIGGER
AFTER UPDATE
ON CUSTM_INFO FOR EACH ROW
BEGIN
IF OLD.FIRST_NAME <> NEW.FIRST_NAME THEN
   INSERT INTO CUSTM_LOG(ID,ACTION,FIELD,OLD_VALUE,NEW_VALUE,UPDATEUSER,UPDATETIMESTAMP)
   VALUES(OLD.ID,"UPDATE","FIRST_NAME",OLD.FIRST_NAME,NEW.FIRST_NAME,USER(),CURRENT_TIMESTAMP());
END IF;
IF OLD.LAST_NAME <> NEW.LAST_NAME THEN
   INSERT INTO CUSTM_LOG(ID,ACTION,FIELD,OLD_VALUE,NEW_VALUE,UPDATEUSER,UPDATETIMESTAMP)
   VALUES(OLD.ID,"UPDATE","FIRST_NAME",OLD.LAST_NAME,NEW.LAST_NAME,USER(),CURRENT_TIMESTAMP());   
END IF;
IF OLD.AGE <> NEW.AGE THEN
   INSERT INTO CUSTM_LOG(ID,ACTION,FIELD,OLD_VALUE,NEW_VALUE,UPDATEUSER,UPDATETIMESTAMP)
   VALUES(OLD.ID,"UPDATE","FIRST_NAME",OLD.AGE,NEW.AGE,USER(),CURRENT_TIMESTAMP());   
END IF;
IF OLD.ADDRESS <> NEW.ADDRESS THEN
   INSERT INTO CUSTM_LOG(ID,ACTION,FIELD,OLD_VALUE,NEW_VALUE,UPDATEUSER,UPDATETIMESTAMP)
   VALUES(OLD.ID,"UPDATE","FIRST_NAME",OLD.ADDRESS,NEW.ADDRESS,USER(),CURRENT_TIMESTAMP());   
END IF;
IF OLD.LOCATION <> NEW.LOCATION THEN
   INSERT INTO CUSTM_LOG(ID,ACTION,FIELD,OLD_VALUE,NEW_VALUE,UPDATEUSER,UPDATETIMESTAMP)
   VALUES(OLD.ID,"UPDATE","FIRST_NAME",OLD.LOCATION,NEW.LOCATION,USER(),CURRENT_TIMESTAMP());   
END IF;
IF OLD.PHONE_NUMBER <> NEW.PHONE_NUMBER THEN
   INSERT INTO CUSTM_LOG(ID,ACTION,FIELD,OLD_VALUE,NEW_VALUE,UPDATEUSER,UPDATETIMESTAMP)
   VALUES(OLD.ID,"UPDATE","FIRST_NAME",OLD.PHONE_NUMBER,NEW.PHONE_NUMBER,USER(),CURRENT_TIMESTAMP());   
END IF;
END
&& 

##---------------VIEWS--------------------------


SELECT * FROM TATA_TB1;
SELECT * FROM TATA_TB2;
SELECT DISTINCT REGION,COUNTRY FROM TATA_TB1;     #NORTH, UNITED KINGDOM

CREATE VIEW NORTHREGION AS(
SELECT A.OrderID,A.CITY,A.COUNTRY,A.REGION,A.SEGMENT,A.STATE,B.DISCOUNT,B.SALES,B.PROFIT,B.QUANTITY
 FROM TATA_TB1 A INNER JOIN TATA_TB2 B ON A.ORDERID = B.ORDERID
WHERE REGION = "NORTH");

SELECT * FROM NORTHREGION;
DESCRIBE NORTHREGION;
INSERT INTO NORTHREGION (OrderID,CITY,COUNTRY,REGION,SEGMENT,STATE,DISCOUNT,SALES,PROFIT,QUANTITY)
VALUES (1234-43,'STOCKHOLM','SWEDEN','NORTH','CONSUMER','ENGLAND',0.4,55,22,4)

INSERT INTO NORTHREGION (OrderID,CITY,COUNTRY,REGION,SEGMENT,STATE)
VALUES (1234-43,'STOCKHOLM','SWEDEN','NORTH','CONSUMER','ENGLAND');

INSERT INTO NORTHREGION (DISCOUNT,SALES,PROFIT,QUANTITY)
VALUES (0.4,55,22,4);


##--------------------------index-----------------------------------------------

SELECT * FROM ELE_STORE WHERE ORDERID = 7119;

ALTER TABLE ELE_STORE ADD INDEX ORDERINDEX(ORDERID);

SELECT * FROM ELE_STORE WHERE ORDERID = 7119;


#------------------CASE STATEMENT---------------------------------

SELECT * FROM CUST_TB;

SELECT *, CASE WHEN CUST_AGE <= 18 THEN "TEEN"
               WHEN CUST_AGE > 18 AND CUST_AGE <= 45 THEN "ADULT"
               WHEN CUST_AGE > 45 THEN "SENIOR CITIZEN" END AS CUSTAGGRP              
               FROM CUST_TB;

#-----------------------CROSS JOIN------------------------------------

CREATE TABLE SHIRT(
SHIRT_SIZE VARCHAR(20));
INSERT INTO SHIRT(SHIRT_SIZE) VALUES("SMALL"),("MEDIUM"),("LARGE"),("XL"),("XXL");
SELECT * FROM SHIRT;

CREATE TABLE COLOR_TB(
COLOR VARCHAR(20));
INSERT INTO COLOR_TB(COLOR) VALUES("RED"),("BLACK"),("WHITE"),("YELLOW"),("BLUE");
SELECT * FROM COLOR_TB;

SELECT A.SHIRT_SIZE, B.COLOR FROM SHIRT A JOIN COLOR_TB B; 

#--------------------3 TABLES JOIN--------------------------------------------------

USE GDB023;

SELECT * FROM DIM_CUSTOMER;
SELECT * FROM DIM_PRODUCT;
SELECT * FROM FACT_SALES_MONTHLY;

SELECT  A.CUSTOMER,A.PLATFORM,A.CHANNEL,A.MARKET,A.REGION, 
        B.PRODUCT_CODE,B.SOLD_QUANTITY,B.DATE,B.FISCAL_YEAR,
        C.DIVISION,C.SEGMENT,C.CATEGORY,C.PRODUCT,C.VARIANT
        FROM DIM_CUSTOMER A LEFT JOIN FACT_SALES_MONTHLY B
        ON A.CUSTOMER_CODE = B.CUSTOMER_CODE  
        LEFT JOIN DIM_PRODUCT C ON B.PRODUCT_CODE = C.PRODUCT_CODE;



select Sub_Category,sum(sales) as totalsales from tata_tb2 group by Sub_Category order by totalsales desc;



select * from tata_tb2;
select a.city,b.totalsales from (
select sum(sales) as totalsales from tata_tb2) as x inner join tata_tb1 b on a.OrderID = b.OrderID;

SELECT distinct(country) FROM TATA_TB1 order by country asc;

SELECT A.CITY, B.TTLSALES FROM TATA_TB1 A INNER JOIN 
(SELECT ORDERID,SUM(SALES) AS TTLSALES FROM TATA_TB2 GROUP BY ORDERID) B ON A.ORDERID = B.ORDERID 
HAVING TTLSALES > 2000 ORDER BY TTLSALES DESC;

SELECT A.CUSTOMERNAME, B.TTLSALES FROM TATA_TB1 A INNER JOIN 
(SELECT ORDERID,SUM(SALES) AS TTLSALES FROM TATA_TB2 GROUP BY ORDERID) B ON A.ORDERID = B.ORDERID 
HAVING TTLSALES > 3000 ORDER BY TTLSALES DESC;

SELECT A.CUSTOMERNAME, B.TTLQTY FROM TATA_TB1 A INNER JOIN 
(SELECT ORDERID,SUM(Quantity) AS TTLQTY FROM TATA_TB2 GROUP BY ORDERID) B ON A.ORDERID = B.ORDERID 
 ORDER BY TTLQTY DESC;


WITH CTE1 AS (
SELECT CITY,ROUND(SUM(SALES),2) AS TOTALSALES FROM SUPER_STORE_TB GROUP BY CITY),
CTE2 AS(SELECT *, RANK() OVER(ORDER BY TOTALSALES DESC) AS RNK FROM CTE1)
SELECT * FROM CTE2 WHERE RNK <=5;

SELECT * FROM COMPANY;
SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;





