SELECT * FROM CAR_DATA; #TO DISPLAY ALL ROWS & COLUMNS.*-->EVERYTHING DISPLAYS

SELECT CAR_NAME,SELLING_PRICE,KMS_DRIVEN FROM CAR_DATA;#BY GIVING COLUMNS,U R DISPALYING SELECTED COLUMNS.

SELECT*FROM CAR_DATA WHERE YEAR=2017; #TO GET ONLY 2017 YEAR CARS

SELECT*FROM CAR_DATA WHERE YEAR=2017 AND FUEL_TYPE='DIESEL'; #TO GET DIESEL TYPE CARS IN THE YEAR OF 2017.

SELECT*FROM CAR_DATA SORT ORDER BY SELLING_PRICE ASC; # FOR SORTING THE SELLING PRICE DATA ASSENDING.

SELECT*FROM CAR_DATA SORT ORDER BY SELLING_PRICE DESC; # FOR SORTING THE SELLING PRICE DATA DESENDING.

SELECT*FROM CAR_DATA SORT ORDER BY KMS_DRIVEN DESC; # FOR SORTING THE KMS DRIVEN BY DESENDING.

SELECT*FROM CAR_DATA SORT ORDER BY KMS_DRIVEN ASC; # FOR SORTING THE KMS DRIVEN BY ASENDING.

SELECT*FROM CAR_DATA LIMIT 7; # LIMIT FUNCTION HELPS YOU TO RESCTRICT THE NO OF ROWS IN TABLE.



SELECT*FROM CAR_DATA WHERE YEAR IN (2017,2018); # IN CONDITION IS USED MULTIPLE VALUES

SELECT*FROM CAR_DATA;
SELECT COUNT(*) FROM CAR_DATA;

SELECT*FROM CAR_DATA WHERE YEAR=2017;
SELECT COUNT(*) FROM CAR_DATA WHERE YEAR=2017; # TO GET THE COUNT WE USE THIS COUNT(*) COMMAND.

SELECT FUEL_TYPE FROM CAR_DATA;

SELECT DISTINCT FUEL_TYPE FROM CAR_DATA; #TO GET TYPE OF DATA WE USED DISTINCT COMMAND. 

SELECT DISTINCT TRANSMISSION FROM CAR_DATA; #TO GET TYPE OF DATA WE USED DISTINCT COMMAND. 

SELECT YEAR FROM CAR_DATA;

SELECT DISTINCT YEAR FROM CAR_DATA; #IT WILL TAKE UNIQUE YEAR

SELECT DISTINCT YEAR FROM CAR_DATA ORDER BY YEAR; # FOR ORDERING THE DATA 

SELECT MIN(YEAR) FROM CAR_DATA; #FOR FIRST YEAR

SELECT MAX(YEAR) FROM CAR_DATA; #FOR LAST YEAR

SELECT MIN(YEAR), MAX(YEAR) FROM CAR_DATA; #FOR FIRST & LAST YEAR DATA 

SELECT*FROM CAR_DATA ORDER BY KMS_DRIVEN DESC LIMIT 1;
SELECT*FROM CAR_DATA ORDER BY KMS_DRIVEN ASC LIMIT 1;  

SELECT MIN(KMS_DRIVEN),MAX(KMS_DRIVEN) FROM CAR_DATA;
 
 SELECT COUNT(*) FROM CAR_DATA WHERE YEAR=2017;#35
 SELECT COUNT(*) FROM CAR_DATA WHERE YEAR=2016;#50
 
 SELECT COUNT(*) FROM CAR_DATA WHERE YEAR IN(2016,2017);
 
 SELECT*FROM CAR_DATA WHERE YEAR IN(2016,2017,2015,2014);
 
SELECT*FROM CAR_DATA WHERE YEAR NOT IN(2016,2017,2015,2014);

 SELECT COUNT(*)FROM CAR_DATA WHERE YEAR IN(2003,2004,2005,2006,2007,2008,2009,2010,2011,2012); #83
 
 SELECT COUNT(*) FROM CAR_DATA WHERE YEAR>=2003 AND YEAR<=2012; #83
 
 SELECT COUNT(*) FROM CAR_DATA WHERE YEAR BETWEEN 2003 AND 2012; #83
 
 SELECT COUNT(*)FROM CAR_DATA WHERE YEAR IN(2004,2006,2008,2010,2012); #50 
 
 SELECT COUNT(*) FROM CAR_DATA WHERE YEAR>=2003 AND YEAR<=2012; 
 
  SELECT*FROM CAR_DATA ;
  
  SELECT COUNT(*) FROM CAR_DATA WHERE KMS_DRIVEN  BETWEEN 500 AND 500000;
  
  SELECT COUNT(*)FROM CAR_DATA WHERE KMS_DRIVEN >= 500;
  
  ---------------------------------------------------------#PL SQL ON 15.11.2022
  
  SELECT COUNT(*) FROM CAR_DATA WHERE YEAR = 2016;
  SELECT COUNT(*) FROM CAR_DATA WHERE YEAR = 2017;
  SELECT COUNT(*) FROM CAR_DATA WHERE YEAR = 2018;
  
  CALL GETCARCOUNTBYYEAR(2017);
  
  DELIMITER **
  CREATE PROCEDURE GETCARDETAILS(IN V_YR INT) #IN-INPUT,V_YR-VARIABLE
  BEGIN
  SELECT COUNT(*) FROM  CAR_DATA WHERE YEAR= V_YR;
  END
  **
  CALL GETCARDETAILS(2012);
  
  
  #GIVE ME TOP 5YAERS WITH HIGHEST SALES CARS COUNT?
  
  SELECT YEAR,COUNT(*) AS NO_OF_CARS FROM CAR_DATA GROUP BY YEAR ORDER BY COUNT(*) DESC LIMIT 5;
  
  DELIMITER **
  CREATE PROCEDURE GETTOP5YEARSSALESCARCOUNT()
  BEGIN
  SELECT YEAR,COUNT(*) AS NO_OF_CARS FROM CAR_DATA GROUP BY YEAR ORDER BY COUNT(*) DESC LIMIT 5;
  END
  **
  
  CALL GETTOP5YEARSSALESCARCOUNT();
  
  
  
 