
CREATE TABLE CUST_INFO(
ID INT PRIMARY KEY, 
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL,
AGE INT CONSTRAINT AGE_LIM1 CHECK (AGE> 18),
ADDRESS VARCHAR(100) UNIQUE, 
LOCATION VARCHAR(20) DEFAULT 'INDIA',
PH_NO BIGINT CONSTRAINT PH_CHECK CHECK (LENGTH (PH_NO)=10),
CONSTRAINT UNIQUE_PH_UK UNIQUE (PH_NO), 
CONSTRAINT FN_LN_CHECK CHECK(FIRST_NAME <> LAST_NAME)
 ); 
 
 SELECT*FROM CUST_INFO_CHECKS_MADE;
 SELECT*FROM CUST_INFO;

 
SELECT*FROM CUST_INFO;

INSERT INTO CUST_INFO VALUES(1,'KIRAN','KUMAR',21,'#35,KORAMANGALA','BANGALORE',7892213354);
INSERT INTO CUST_INFO VALUES(2,'KARTHIK','RAJ',25,'#38,WHITEFIELD','BANGALORE',7892213439);
INSERT INTO CUST_INFO VALUES(3,'RAHUL','RAHUL',35,'#2,GREENGARDEN','CHENNAI',7846783439);
INSERT INTO CUST_INFO VALUES(4,'HEMA','MALINI',19,'#2,ROUTUNGARDEN','PUNE',7846783439);
INSERT INTO CUST_INFO (ID,FIRST_NAME,LAST_NAME,AGE,ADDRESS,PH_NO)
VALUES(5,'RAJEEV','BP',25,'#21,KR NAGAR',7846783674);
INSERT INTO CUST_INFO (ID,FIRST_NAME,LAST_NAME,AGE,ADDRESS,PH_NO)
VALUES(6,'DIVI','KUMARI	',28,'#21,MTR STREET',7846783456);

DELETE FROM CUST_INFO WHERE ID=3;

SELECT*FROM CUST_INFO;