CREATE TABLE CUSTUMER_TB(ID INT(5),
             NAME VARCHAR(20), 
             AGE TINYINT(10) ,ADDRESS VARCHAR(50), 
             WALLET_BAL FLOAT(10));
			 
INSERT INTO CUSTUMER_TB VALUES (1,"RAMESH",32,"AHMEDABAD",200);
INSERT INTO CUSTUMER_TB VALUES (2,"KHILAN",23,"DELHI",7500);
INSERT INTO CUSTUMER_TB VALUES (3,"KAUSHIK",25,"KOTA",12000);
INSERT INTO CUSTUMER_TB VALUES (4,"CHAITALI",22,"MUJMBAI",6500);
INSERT INTO CUSTUMER_TB VALUES (5,"HARDIK",27,"BHOPAL",600);
INSERT INTO CUSTUMER_TB VALUES (6,"KOMAL",26,"MP",750);
INSERT INTO CUSTUMER_TB VALUES (7,"MUFFY",27,"INDORE",500);

DROP TABLE IF EXISTS ORDER_TB;
CREATE TABLE ORDER_TB (
             OID INT,
			 DATE DATE,
			 C_ID VARCHAR(3),
			 AMOUNT FLOAT); 
			 
INSERT INTO ORDER_TB VALUES (102,"2009-10-08",'3',3000);
INSERT INTO ORDER_TB VALUES (100,"2009-10-08",'3',1500);
INSERT INTO ORDER_TB VALUES (101,"2009-11-20",'2',1560);
INSERT INTO ORDER_TB VALUES (103,"2009-05-20",'4',2060);
INSERT INTO ORDER_TB (OID,DATE,AMOUNT) VALUES (199,"2020-05-20",9999);
INSERT INTO ORDER_TB (OID,DATE,AMOUNT) VALUES (200,"2022-11-10",8989);
SELECT*FROM CUSTUMER_TB;

SET SQL_SAFE_UPDATES=1;

DELETE FROM ORDER_TB WHERE OID=200;
SELECT*FROM ORDER_TB;

SELECT*FROM AMAZON_DB.CUSTUMER_TB;

SELECT ID,NAME,AGE,ADDRESS,WALLET_BAL FROM CUSTUMER_TB;
SELECT ID,NAME,AGE,ADDRESS,WALLET_BAL FROM AMAZON_DB.CUSTUMER_TB;
SELECT CUSTUMER_TB.ID,CUSTUMER_TB.NAME,CUSTUMER_TB.AGE,CUSTUMER_TB.ADDRESS,CUSTUMER_TB.WALLET_BAL FROM AMAZON_DB.CUSTUMER_TB; 

SELECT A.ID,A.NAME,A.AGE,A.ADDRESS,A.WALLET_BAL FROM CUSTUMER_TB AS A;


SELECT*FROM CUSTUMER_TB;

SELECT*FROM ORDER_TB;

SELECT A.NAME,A.ADDRESS FROM CUSTUMER_TB AS A;
SELECT B.OID,B.DATE FROM ORDER_TB AS B;

#REQUIREMENT INNER JOIN

SELECT A.NAME,A.ADDRESS,B.OID,B.DATE FROM CUSTUMER_TB A INNER JOIN ORDER_TB B ON A.ID=B.C_ID;

#REQUIRE LEFT JOIN

SELECT A.NAME,A.ADDRESS,B.OID, B.DATE FROM CUSTUMER_TB A LEFT JOIN ORDER_TB B ON A.ID=B.C_ID;

#HOW MANY CUSTUMER ARE THERE IN AMAZON?
SELECT DISTINCT A.NAME FROM CUSTUMER_TB A LEFT JOIN ORDER_TB B ON A.ID=B.C_ID;
#HOW MANY CUSTUMER ARE THERE IN AMAZON?
SELECT COUNT(DISTINCT A.NAME) FROM CUSTUMER_TB A LEFT JOIN ORDER_TB B ON A.ID=B.C_ID;

#HOW MANY CUSTUMER HAVE NOT PURCHASED IN AMAZON?
SELECT A.NAME,A.ADDRESS,B.OID, B.DATE FROM CUSTUMER_TB A LEFT JOIN ORDER_TB B ON A.ID=B.C_ID WHERE B.OID IS NULL;
SELECT COUNT(DISTINCT A.NAME) NOT_PURCHASED_CUSTs FROM CUSTUMER_TB A LEFT JOIN ORDER_TB B ON A.ID=B.C_ID WHERE B.OID IS NULL;

#HOW MANY CUSTUMER HAVE PURCHASED IN AMAZON?
SELECT COUNT(DISTINCT A.NAME) PURCHASED_CUSTS FROM CUSTUMER_TB A LEFT JOIN ORDER_TB B ON A.ID=B.C_ID WHERE B.OID IS NOT NULL; 

#HOW MANY GUEST ORDERS ARE THERE?
#RIGHT JOIN.
SELECT A.NAME,A.ADDRESS,B.OID, B.DATE FROM CUSTUMER_TB A RIGHT JOIN ORDER_TB B ON A.ID=B.C_ID;


#FULL JOIN # FULL JOIN NOT SUPPORTED TO MY SQL. BUT WE CAN JOINS THE TABLE BY USING #UNION COMMAND(LEFT & RIGHT JOIN)

SELECT A.NAME,A.ADDRESS,B.OID, B.DATE FROM CUSTUMER_TB A LEFT JOIN ORDER_TB B ON A.ID=B.C_ID
UNION 
SELECT A.NAME,A.ADDRESS,B.OID, B.DATE FROM CUSTUMER_TB A RIGHT JOIN ORDER_TB B ON A.ID=B.C_ID;

#UNION ALL (IT GIVES DUPLICATE VALUES)

SELECT A.NAME,A.ADDRESS,B.OID, B.DATE FROM CUSTUMER_TB A LEFT JOIN ORDER_TB B ON A.ID=B.C_ID
UNION  ALL
SELECT A.NAME,A.ADDRESS,B.OID, B.DATE FROM CUSTUMER_TB A RIGHT JOIN ORDER_TB B ON A.ID=B.C_ID;


