CREATE TABLE CUSTOMER_INF1(CUST_ID INT(5),
             CUST_NAME VARCHAR(20), 
             AGE TINYINT(10) ,ADDRESS VARCHAR(50), 
             WALLET_BAL FLOAT(10));
SELECT*FROM CUSTOMER_INF1; 

INSERT INTO CUSTOMER_INF1 VALUES (1,"RAMESH",32,"AHMEDABAD",200);
INSERT INTO CUSTOMER_INF1 VALUES (2,"KHILAN",23,"DELHI",7500);
INSERT INTO CUSTOMER_INF1 VALUES (3,"KAUSHIK",25,"KOTA",12000);
INSERT INTO CUSTOMER_INF1 VALUES (4,"CHAITALI",22,"MUJMBAI",6500);
INSERT INTO CUSTOMER_INF1 VALUES (5,"HARDIK",27,"BHOPAL",600);
INSERT INTO CUSTOMER_INF1 VALUES (6,"KOMAL",26,"MP",750);
INSERT INTO CUSTOMER_INF1 VALUES (7,"MUFFY",27,"INDORE",500);


CREATE TABLE ORDER_TB (
             OID INT,
			 DATE DATE,
			 C_ID VARCHAR(3),
			 AMOUNT FLOAT); 
SELECT*FROM ORDER_TB;
			 
INSERT INTO ORDER_TB VALUES (102,"2009-10-08",'3',3000);
INSERT INTO ORDER_TB VALUES (100,"2009-10-08",'3',1500);
INSERT INTO ORDER_TB VALUES (101,"2009-11-20",'2',1560);
INSERT INTO ORDER_TB VALUES (103,"2009-05-20",'4',2060);
INSERT INTO ORDER_TB VALUES (199,"2020-05-20",'',9999);

DELETE FROM ORDER_TB WHERE (OID=199);

SET SQL_SAFE_UPDATES=0;


SELECT COUNT(*) AS TOTAL_CUSTA_IN_AMAZON FROM CUSTOMER_INF1;

SELECT CUST_NAME FROM CUSTOMER_INF1;

SELECT*FROM CUSTOMER_INF1; 
SELECT*FROM ORDER_TB;

SELECT CUST_NAME FROM CUSTOMER_INF1 WHERE CUST_ID IN(2,3,4); #CUSTOMERS WHO HAVE PIURCHASED


SELECT CUST_ID FROM CUSTOMER_INF1 WHERE CUST_ID IN(2,3,4);

SELECT CUST_NAME FROM CUSTOMER_INF1 WHERE CUST_ID IN (SELECT DISTINCT C_ID FROM ORDER_TB);

SELECT CUST_NAME FROM CUSTOMER_INF1 WHERE CUST_ID NOT IN (SELECT DISTINCT C_ID FROM ORDER_TB);