SELECT YEAR FUEL_TYPE,COUNT(*)FROM CAR_DATA GROUP BY YEAR,FUEL_TYPE ORDER BY YEAR;

SELECT YEAR FUEL_TYPE, COUNT(*) FROM CAR_DATA 
WHERE YEAR IN (2013,2014,2015,2016,2017)
GROUP BY YEAR ORDER BY YEAR;

SELECT YEAR FUEL_TYPE, COUNT(*) FROM CAR_DATA
GROUP BY YEAR HAVING COUNT(*) >30 ORDER BY YEAR; #HAVING CONDITION IS USED TO FILTER THE AGGRGATED COLUMN.  
SELECT * FROM CAR_DATA;
SELECT CAR_NAME,SUM(SELLING_PRICE) FROM CAR_DATA WHERE CAR_NAME='RITZ'; #11.45 
SELECT CAR_NAME, SUM(SELLING_PRICE) FROM CAR_DATA  WHERE CAR_NAME='CIAZ'; #67.25

SELECT CAR_NAME, SUM(SELLING_PRICE) FROM CAR_DATA GROUP BY CAR_NAME HAVING SUM(SELLING_PRICE) > 5; 

SELECT SUM(SELLING_PRICE) FROM CAR_DATA WHERE FUEL_TYPE = 'PETROL' AND TRANSMISSION='MANUAL'; #651.729


SELECT SUM(SELLING_PRICE) FROM CAR_DATA WHERE FUEL_TYPE = 'PETROL' AND TRANSMISSION='AUTOMATIC'; #128.41 

SELECT FUEL_TYPE, SUM(PRESENT_PRICE),SUM(SELLING_PRICE) FROM CAR_DATA GROUP BY FUEL_TYPE, TRANSMISSION ORDER BY FUEL_TYPE;

SELECT YEAR,COUNT(*) AS TOTAL_CARS FROM CAR_DATA GROUP BY YEAR ORDER BY YEAR;

SELECT * FROM CAR_DATA; 
SELECT * FROM (CAR_DATA);

SELECT*FROM (SELECT*FROM CAR_DATA) AS TEMP; 

SELECT YEAR,COUNT(*) AS TOTAL_CARS FROM CAR_DATA GROUP BY YEAR ORDER BY YEAR;

SELECT*FROM (SELECT YEAR,COUNT(*) AS TOTAL_CARS FROM CAR_DATA GROUP BY YEAR ORDER BY YEAR) 
AS TEMP WHERE TOTAL_CARS>25; 

