SET AUTOCOMMIT=0;  #BY DEFAULT MYSQL IS AUTO COMMIT(1), SO SETTING TO 0, SO THAT I HAVE CONTROL, WHEN TO SAVE , WHEN NOT TO SAVE..

SELECT DATABASE(); 

SHOW TABLES;
USE AMAZON_DB;

CREATE TABLE TCL_TB(ID INT, NAME VARCHAR(20), AGE INT);
SELECT*FROM TCL_TB;
INSERT INTO TCL_TB VALUES (1,'RAJA',25);
INSERT INTO TCL_TB VALUES (2,'ANIL',26);
INSERT INTO TCL_TB VALUES (3,'RAMU',24);
INSERT INTO TCL_TB VALUES (4,'ANAD',22);
INSERT INTO TCL_TB VALUES (5,'HARI',20);
START TRANSACTION; #TO START A CODE

SET SQL_SAFE_UPDATES=0;
DELETE FROM TCL_TB;
ROLLBACK; 
SELECT*FROM TCL_TB;
ROLLBACK; #TO ROLL BACK DELETED DATA.
SELECT*FROM TCL_TB;

START TRANSACTION ; 
DELETE FROM TCL_TB WHERE NAME='RAJA';  

ROLLBACK;
SELECT*FROM TCL_TB;

START TRANSACTION;
SELECT*FROM TCL_TB;
UPDATE TCL_TB SET AGE = 99 WHERE NAME='RAJA';
UPDATE  TCL_TB SET AGE = 99 WHERE NAME = 'HARI'; 
SELECT*FROM TCL_TB;
ROLLBACK;

START TRANSACTION; 
SAVEPOINT A; 
INSERT INTO TCL_TB VALUES (6,'NEWPERSON',25); 
SELECT*FROM TCL_TB; 
SAVEPOINT B;
UPDATE TCL_TB SET AGE = 99 WHERE NAME='RAMU';
SELECT*FROM TCL_TB;
SAVEPOINT C;
DELETE FROM TCL_TB WHERE ID = 1;
DELETE FROM TCL_TB WHERE ID = 2;
DELETE FROM TCL_TB WHERE ID = 3;
SELECT*FROM TCL_TB;
ROLLBACK TO C;


SELECT*FROM TCL_TB; 
UPDATE TCL_TB SET AGE = 100 WHERE ID=1;
UPDATE TCL_TB SET AGE = 100 WHERE ID=2;
SELECT*FROM TCL_TB;
COMMIT; #CONFIRMED TO DATABASE...TELLING THET.. THIS IS CORRECT.. 
UPDATE TCL_TB SET AGE = 100 WHERE ID=3;
UPDATE TCL_TB SET AGE = 100 WHERE ID=4;
ROLLBACK; 
SELECT*FROM TCL_TB; 
START TRANSACTION;
SELECT*FROM TCL_TB; 
UPDATE TCL_TB SET AGE = 100 WHERE ID=1;
UPDATE TCL_TB SET AGE = 100 WHERE ID=2;
SELECT*FROM TCL_TB;
COMMIT; #CONFIRMED TO DATABASE...TELLING THET.. THIS IS CORRECT.. 
UPDATE TCL_TB SET AGE = 100 WHERE ID=3;
UPDATE TCL_TB SET AGE = 100 WHERE ID=4;
ROLLBACK; 
SELECT*FROM TCL_TB; 
START TRANSACTION;
INSERT INTO TCL_TB VALUES (7,'PERSON',24);
INSERT INTO TCL_TB VALUES (8,'LADY',29);

UPDATE TCL_TB SET AGE = 90 WHERE ID=5;
UPDATE TCL_TB SET AGE = 900 WHERE ID=6;
SELECT*FROM TCL_TB; 
COMMIT; 
UPDATE TCL_TB SET AGE = 77 WHERE ID=7;
UPDATE TCL_TB SET AGE = 77 WHERE ID=8;
SELECT*FROM TCL_TB; 
ROLLBACK; 
SELECT*FROM TCL_TB; 
